### PR TITLE
Add static libraries for Windows ARM64 + Linux ARM64

### PR DESCRIPTION
**Pull request by dennisameling**
Similar to https://github.com/EvanHahn-Signal/node-sqlcipher/pull/1

Adds statically linked binaries for OpenSSL Windows ARM64. Generated with `vcpkg`: `.\vcpkg\vcpkg install openssl:arm64-windows-static`

Needed for https://github.com/signalapp/Signal-Desktop/issues/3745#issuecomment-783263701

Also done in the main `journeyapps/node-sqlcipher` repo (which did updates recently as well): https://github.com/journeyapps/node-sqlcipher/pull/75

Can confirm that the generated ARM64 `better_sqlite3.node` allows Signal Desktop ARM64 to boot without any problems:

image

### CODE REVIEW

**Comment by dennisameling** [comment]
@indutny-signal is this PR being considered? If yes then I'll make sure to resolve conflicts. I added static libraries both for Windows ARM64 and Linux ARM64.

This is the final native dependency for Signal Desktop that doesn't have "official" Windows ARM64 and Linux ARM64 functionality by the Signal team. `ringrtc` and `signal-client` now provide those native libraries for said platforms:

- https://github.com/signalapp/ringrtc/issues/40
- https://github.com/signalapp/libsignal-client/pull/440
- https://github.com/signalapp/libsignal-client/pull/450

Thanks in advance for your consideration!

**Comment by BugInACode** [comment]
@dennisameling the app is currently being developed to run on arm64 devices and requires `better-sqlcipher` to have arm64 compatibility. 

Is there anything I can do to help make this happen?

**Comment by indutny-signal** [comment]
@dennisameling thanks so much for this PR. I used vcpkg to reproduce the results of it and ended up with this commit https://github.com/signalapp/better-sqlite3/commit/cbffcb3ab8a945bff3b3829187cf4c6af0865ee4 . Could you give it a try sometime, please?

I'll see if I can do arm64 linux builds tomorrow.

Thank you!

**Comment by dennisameling** [comment]
@indutny-signal thanks for your support with this! First I got this error:

image

Then I realized that you removed that code [here](https://github.com/signalapp/better-sqlite3/commit/b7c82cbde05f6b115fdc0b331c25650477d692b0) so that it's no longer available to Signal Desktop.

I reverted your commit from the `signalapp/Signal-Desktop` repo (https://github.com/signalapp/Signal-Desktop/commit/1b1ed2cd057817c5ce0bade62bfd8d6e1650880a) and then got another error:

```
Database startup error:

Error: Error: Could not locate the bindings file. Tried:
 → [REDACTED]\node_modules\better-sqlite3\build\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\Release\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\compiled\16.13.0\win32\arm64\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → [REDACTED]\node_modules\better-sqlite3\lib\binding\node-v101-win32-arm64\better_sqlite3.node
    at bindings ([REDACTED]\node_modules\bindings\bindings.js:126:9)
    at new Database ([REDACTED]\node_modules\better-sqlite3\lib\database.js:48:64)
    at openAndMigrateDatabase ([REDACTED]\ts\sql\Server.js:308:8)
    at openAndSetUpSQLCipher ([REDACTED]\ts\sql\Server.js:325:14)
    at Object.initialize ([REDACTED]\ts\sql\Server.js:355:10)
    at MessagePort.<anonymous> ([REDACTED]\ts\sql\mainWorker.js:80:35)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.<anonymous> ([REDACTED]\ts\sql\main.js:61:26)
    at Worker.emit (node:events:390:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

When I go into the `node_modules\better-sqlite3` folder and build from there, it correctly builds the `better_sqlite3.node` file. It just doesn't do that when I do `yarn build` in the `signal-desktop` repo.

I just tried the exact same thing in the official `signalapp/signal-desktop` repo by simply referencing your commit on a x64 machine, but it has the same problem. Tried it on two different devices and had the same issue, so it should be pretty easy to reproduce.

Again, thanks for working on this, and let me know if I can test anything else! 🙏🏼

**Comment by indutny-signal** [comment]
I can reproduce it too. Thanks!

```
43 error sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_key_length [C:\Users\indutny\Code\better-test\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
43 error sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_nid [C:\Users\indutny\Code\better-test\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
43 error sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_block_size [C:\Users\indutny\Code\better-test\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
43 error sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_MD_size [C:\Users\indutny\Code\better-test\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
43 error sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_iv_length [C:\Users\indutny\Code\better-test\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
```

Looks like this is the issue. Debugging.

**Comment by indutny-signal** [comment]
I think it could be the include files. Looks like I messed them up a bit. :joy:

**Comment by indutny-signal** [comment]
Hm... @dennisameling did you use `vcpkg/packages/openssl_x64-windows-static/lib/libcrypto.lib` (and similar for arm64) when you originally opened this PR, or some other file?

**Comment by dennisameling** [comment]
I used `vcpkg/packages/openssl-arm64-windows-static/lib/libcrypto.lib` indeed. So weird... 😅

**Comment by indutny-signal** [comment]
Thanks for confirming this. Somehow your tar.gz file works while my doesn't 😅 I've renamed the folders, but it shouldn't be that. Will keep you updated on what I discover.

**Comment by indutny-signal** [comment]
Hah, there are some missing symbols that are really not in the lib file. This is getting weird!

**Comment by indutny-signal** [comment]
Oh lol, I built OpenSSL 3.0.2 :joy:

**Comment by indutny-signal** [comment]
Alright. It is fixed now @dennisameling . If you'd get a chance - I'd appreciate you giving it a try. Thanks!

**Comment by dennisameling** [comment]
Was going to mention OpenSSL v3 indeed, but then I checked https://vcpkg.io/en/packages.html and it still mentions 1.1.1n, so thought that v3 couldn't be the problem 😅 

In any case, it's working correctly now! Thank you so much! 🎉

**Comment by balupton** [comment]
Just a bump in case this fell to the wayside. This seems to be the last remaining task for arm64 support right?

**Comment by indutny-signal** [comment]
Windows ARM64 is already here, but I didn't do the Linux build just yet.

**Comment by BugInACode** [comment]
As a regular linux user, is there anything I can provide to help complete the arm64 compatibility for linux?

**Comment by indutny-signal** [comment]
Just pushed arm64 build artifact. Let me know if it works!

**Comment by dennisameling** [comment]
@indutny-signal it seems to work, thanks! https://app.circleci.com/pipelines/github/dennisameling/Signal-Desktop/41/workflows/a44dcf04-c0fe-4f16-95c7-4683c642e198/jobs/32

Will just need to fix an issue with `electron-builder` but that's unrelated to this (one of their binaries doesn't support arm64 yet)

**Pull request closed without merging**
